version: '3'

services:
  socket:
    build: .
    volumes:
      - ./src:/usr/src/app
    ports:
      - "8070:8000"
    depends_on:
      - redis
    command: python antares_api/manage.py runserver 0.0.0.0:8000
  redis:
    image: redis
    volumes:
      - ./data:/data
    ports:
      - "6380:6379"
