version: '3'

services:
  socket:
    build: .
    volumes:
      - ./src:/usr/src/app
    ports:
      - "9800:8000"
    command: ['python antares_api/manage.py runserver']
  redis:
    image: redis
    volumes:
      - ./data:/data
    ports:
      - "6379:6379"


